import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { FaRegCheckCircle } from "react-icons/fa";
import { getAboutus, getMissionVission, getSiteData, getTeams } from "@/lib/functions";

export async function generatemetadata() {
  return {
    title: "About Us",
    description: "Generated by R R Grow Wealth.",
  };
}

export default async function AboutUs() {
  const siteSettings = await getSiteData();
  const missionvission = await getMissionVission();
  const teams = await getTeams();
  const aboutus = await getAboutus();

  function createMarkup(item) {
    return { __html: item || "" };
  }

  return (
    <div>
      {/* Hero Section */}
      <div className="flex bg-center bg-no-repeat bg-cover bg-[url('/images/pay-premium/pay-premium.webp')] overflow-hidden text-start justify-start items-center h-64">
        <div className="max-w-screen-xl mx-auto">
          <h1 className="text-gray-900 text-3xl md:text-5xl font-bold">
            Welcome to {siteSettings?.websiteName}
          </h1>
        </div>
      </div>

      {/* Introduction Section */}
      <section className="md:my-20 my-10 md:px-0 px-3">
        <h2 className="text-4xl text-[var(--rv-primary)] md:text-5xl font-bold mb-6 text-center">
          About Us
        </h2>
        <p className="text-gray-800 max-w-5xl mx-auto text-center mb-5">
          {siteSettings?.websiteName} is a Wealth Management/Financial Planning Firm. This Firm is run by professionals and experienced management. Our expertise is in "Need-Based Financial Planning" which helps our customers achieve their Financial Goals with proper Risk Management.
        </p>

        {/* Top Features Section */}
        <h3 className="text-3xl text-center font-semibold text-[var(--rv-primary)] mb-6">
          Our Top Features
        </h3>
        <div className="grid md:grid-cols-3 sm:grid-cols-2 grid-cols-1 gap-6 max-w-6xl mx-auto px-4">
          {[
            "250+ Crore AUM",
            "Serving 1500+ Clients",
            "20+ Qualified Team Members",
            "Cutting Edge Technology",
            "30+ Years Combined Experience",
            "35+ Research Tools",
          ].map((feature, index) => (
            <div key={index} className="bg-white rounded-xl shadow-md p-6 text-center hover:shadow-lg transition duration-300">
              <p className="text-lg font-medium text-gray-800">{feature}</p>
            </div>
          ))}
        </div>
      </section>

      {/* About Us Detailed Section */}
      <div className="bg-[var(--rv-secondary)]">
        <div className="max-w-screen-xl mx-auto md:py-20 py-10 md:px-0 px-3">
          <section className="grid grid-cols-1 md:grid-cols-2 gap-12 mb-6 items-center">
            <div className="relative">
              <Image
                src={aboutus[0]?.image?.url}
                alt="About Us"
                width={550}
                height={550}
                className="rounded-xl grayscale shadow-lg"
              />
            </div>
            <div>
              <h2 className="text-3xl text-white md:text-4xl font-bold mb-6">
                {aboutus[0]?.title}
              </h2>
              <div
                dangerouslySetInnerHTML={createMarkup(aboutus[0]?.description)}
                className="text-gray-100 mb-6"
              />
            </div>
          </section>
        </div>
      </div>

      {/* Mission, Vision, Core Values */}
      <div className="max-w-screen-xl mx-auto md:py-20 py-10 md:px-0 px-3">
        <section className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
          <div className="group bg-[var(--rv-primary)] p-6 rounded-xl shadow-lg hover:scale-105 transition-transform">
            <h3 className="text-2xl font-bold text-white my-3">Our Mission</h3>
            <p className="text-gray-100">{missionvission?.mission}</p>
          </div>
          <div className="group bg-[var(--rv-primary)] p-6 rounded-xl shadow-lg hover:scale-105 transition-transform">
            <h3 className="text-2xl font-bold text-white my-3">Our Vision</h3>
            <p className="text-gray-100">{missionvission?.vision}</p>
          </div>
        </section>

        <section className="mb-16">
          <h3 className="text-3xl font-semibold text-[var(--rv-primary)] text-center mb-6">
            Core Values
          </h3>
          <p className="text-center max-w-3xl mx-auto text-gray-700 mb-4">
            We firmly believe that our Core Values have served as the Cornerstone for the Expansion and Success of our Company.
          </p>
          <ul className="grid sm:grid-cols-2 md:grid-cols-3 gap-4 text-center max-w-4xl mx-auto">
            {[
              "Financial Education",
              "Commitment",
              "Speed",
              "Transparency",
              "Client Centric Approach",
            ].map((value, i) => (
              <li
                key={i}
                className="bg-gray-100 p-4 rounded-lg shadow text-[var(--rv-primary)] font-semibold"
              >
                {value}
              </li>
            ))}
          </ul>
        </section>
      </div>

      {/* Team Section */}
      <div className="bg-[var(--rv-secondary)]">
        <div className="max-w-screen-xl mx-auto md:py-20 py-10 md:px-0 px-3">
          <section className="mb-20">
            <h2 className="text-2xl md:text-4xl lg:text-5xl font-bold text-white mb-12 text-center">
              Meet the Minds Powering the Future of Wealth Management
            </h2>
            <div className="group bg-[var(--rv-primary)] p-8 rounded-xl shadow-lg transition-transform transform hover:scale-105 hover:shadow-2xl mb-10">
              <div className="grid md:grid-cols-6 justify-center gap-5">
                <div className="md:col-span-2">
                  <Image
                    src={teams[0]?.image?.url}
                    alt={teams[0]?.name}
                    width={380}
                    height={380}
                    className="rounded grayscale group-hover:grayscale-0 transition-all mr-4"
                  />
                </div>
                <div className="md:col-span-4">
                  <h3 className="text-2xl font-bold text-white mb-4">{teams[0]?.name}</h3>
                  <div
                    dangerouslySetInnerHTML={createMarkup(teams[0]?.description)}
                    className="text-gray-100 mb-4"
                  />
                  <h4 className="text-xl font-semibold text-white mb-2">Quick Bio</h4>
                  <ul className="list-disc pl-5 space-y-2 text-gray-100">
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      CFP (FPSB - Financial Planning Standard Board, USA)
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      CFGP (AAFM - American Academy of Financial Management)
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      30+ Certification courses related to Financial Markets (BSE, NSE, AMFI, etc.)
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      B.Com (South Gujarat University)
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      Author of the book "Mera Wealth Plan"
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      Writes financial articles for Divyabhaskar, Gujarat Samachar, Gujarat Guardian
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>

      {/* Call to Action Section */}
      <div className="max-w-screen-xl mx-auto py-20">
        <section className="text-center">
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Join Us on a Journey to Infinite Growth!
          </h2>
          <p className="text-gray-700 max-w-3xl mx-auto mb-8">
            At {siteSettings?.websiteName}, we don’t just manage wealth—we shape financial futures. Join us in transforming financial growth for business owners across India. Together, we’ll redefine what’s possible.
          </p>
          <Link href="/contact-us">
            <button className="primarybutton">
              Get Started
            </button>
          </Link>
        </section>
      </div>
    </div>
  );
}
